import Image from 'next/image'
import { useAuth } from '../context/AuthContext'
import Login from './login'

export default function Home() {
  const {currentUser} =useAuth()
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <UserDashboard/>}
    </>
  )
}
